<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Ap-Hospital [
               <!ELEMENT Ap-Hospital (patient)*>
               <!ELEMENT patient (age,disease,date)>
               <!ELEMENT age (#PCDATA)>
               <!ELEMENT disease (#PCDATA)>
               <!ELEMENT date (#PCDATA)>
]>
<Ap-Hospital>
               <patient>
                              <age>21</age>
                              <disease>Fever</disease>
                              <date>2022-10-1</date>
               </patient>
               <patient>
                              <age>61</age>
                              <disease>Headache</disease>
                              <date>2022-16-1</date>
               </patient>
               <patient>
                              <age>90</age>
                              <disease>Chest Infection</disease>
                              <date>2022-20-1</date>
               </patient>
</Ap-Hospital>